MilestoneEventStatusTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: shipment-and-milestone-event-status-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES        