---
function:
  handler: ${self:custom.alias}/src/create_sns_topics.handler
  name: ${self:service}-create-sns-topics-${self:provider.stage}
  description: create sns topics API - ${self:provider.stage}
  layers:
    - Ref: PythonRequirementsLambdaLayer   
  events: 
    - http:  
        path: /events
        method: POST
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            400:
              pattern: '.*httpStatus\": 400.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            409:
              pattern: '.*httpStatus\": 409.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}    
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    exclude:
    - '**/*'
    include:
    - ${self:custom.alias}/src/create_sns_topics.py
  environment: 
    EVENTING_TOPICS_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/topics/table/name}
    REGION: ${self:provider.region}