---
function:
  handler: src/createSubscription.handler
  name: ${self:service}-create-subscription-${self:provider.stage}
  description: create subscription Webhook API - ${self:provider.stage}
  events: 
    - http:  
        path: /webhook
        method: POST
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    include:
    - src/createSubscription.py
  environment: 
    EVENTING_TOPICS_TABLE: ${ssm:/omni/eventing/topics/table}
    CUSTOMER_PREFERENCE_TABLE : ${ssm:/omni/eventing/preferences/table}
    CUSTOMER_PREFERENCE_TABLE_INDEX: ${ssm:/omni/eventing/preferences/table/Index}
    REGION: ${self:provider.region}