---
function:
  handler: ${self:custom.alias}/src/create_subscription.handler
  name: ${self:service}-create-subscription-${self:provider.stage}
  description: create subscription Webhook API - ${self:provider.stage}
  layers:
    - Ref: PythonRequirementsLambdaLayer  
  events: 
    - http:  
        path: /webhook
        method: POST
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            400:
              pattern: '.*httpStatus\": 400.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}  
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    exclude:
    - '**/*'
    include:
    - ${self:custom.alias}/src/create_subscription.py
    - __pycache__/**
    - _pyrsistent_version.py
    - attr/**
    - attrs/**
    - attrs-23.1.0.dist-info/**
    - bin/**
    - decorator-5.1.1.dist-info/**
    - decorator.py
    - jsonschema/**
    - jsonschema-4.15.0.dist-info/**
    - pvectorc.cpython-311-darwin.so
    - pydash/**
    - pydash-5.0.1.dist-info/**
    - pyrsistent/**
    - pyrsistent-0.20.0.dist-info/**
    - typing_extensions-4.3.0.dist-info/**
    - typing_extensions.py
    - validators/**
    - validators-0.20.0.dist-info/**    
  environment: 
    EVENTING_TOPICS_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/topics/table/name}
    CUSTOMER_PREFERENCE_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/preferences/table/name}
    REGION: ${self:provider.region}