function:
  name: ${self:service}-diff-pipeline-${self:service}
  handler: src/datapipelineDiff.handler
  events:
    - sns: 
        arn: ${ssm:/omni/${self:provider.stage}/eventing/sns/diff-data-pipeline/arn}
  package:
    include:
    - src/datapipelineDiff.py

  environment:
    DBNAME: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    USER: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    CLUSTERID: ${ssm:/omni-dw/${self:provider.stage}/cluster/identifier}
    BUCKET: ${ssm:/omni-dw/${self:provider.stage}/s3/datapipeline/bucket}
    KEY: ${ssm:/omni-dw/${self:provider.stage}/s3/eventing-diff/key}
