---
function:
  handler: ${self:custom.alias}/src/get_event_types.handler
  name: ${self:service}-get-event-types-${self:provider.stage}
  description: get all events types API - ${self:provider.stage}
  layers:
    - Ref: PythonRequirementsLambdaLayer    
  events: 
    - http:  
        path: /events
        method: GET
        integration: lambda
        private: true
        authorizer: 
          name: custom-authorizer
          identitySource: method.request.header.x-api-key
          type: request
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ''
            501:
              pattern: '.*httpStatus\": 501.*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  package:
    exclude:
    - '**/*'
    include:
    - ${self:custom.alias}/src/get_event_types.py
  environment: 
    EVENTING_TOPICS_TABLE: ${ssm:/omni/${self:provider.stage}/eventing/topics/table/name}
    REGION: ${self:provider.region}

