function:
  handler: ${self:provider.alias}/src/s3Event.handler
  name: ${self:service}-s3-event-trigger-${self:provider.stage}
  description: omni eventing trigger state machine - events from s3 - ${self:provider.stage}
  memorySize: 2048
  timeout: 900
  package:
    exclude:
    - '**/*'
    include:
    - ${self:provider.alias}/src/s3Event.py

  events:
    - s3:
        bucket: dw-ps-dev
        event: s3:ObjectCreated:*
        rules:
          - prefix: dev-diff-shipment-info/
          - suffix: .csv000
        existing: true
  environment:
    SM_ARN: arn:aws:states:${self:custom.${self:provider.stage}.region}:${self:custom.${self:provider.stage}.account}:stateMachine:omni-eventing-sns-publish-state-machine-${self:provider.stage}
