---
stateMachine:
  name: ${self:service}-publish-sns-events-state-machine-${self:provider.stage}
  definition:
    Comment: 'State machine to publish sns notifications from S3'
    StartAt: publishSNSEvents
    States:
      publishSNSEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-publish-sns-events-${self:provider.stage}"
        End: true
  